name: assignment3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./meals-service
          file: ./meals-service/Dockerfile
          tags: meals-service:latest
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meals-service
          path: /tmp/image.tar
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Load Docker images from previous workflows
        run: docker load --input meals-service/image.tar
      - name: Check meals-service image is loaded
        run: docker image ls
      - name: Run image in container
        run: docker run -p 8000:8000 meals-service &
      - name: Check container is running
        run: docker ps